changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
  categories:
    - title: "New Features "
      labels:
        - feature
        - enhancement
        - new-feature
    - title: "Bug Fixes"
      labels:
        - bug
        - bugfix
        - fix
    - title: "Notes"
      labels:
        - documentation
        - notes
        - improvement
        - refactor
    - title: "Other Changes"
      labels:
        - "*"
